version: 2

aliases:
  database: &database
    image: circleci/postgres:10-ram
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_DB: handcuffs_test
      POSTGRES_HOST_AUTH_METHOD: trust

  test_env: &test_env
    - PGHOST=localhost
    - PGUSER=ubuntu
    - RAILS_ENV=test
    - BUNDLER_VERSION=1.17.3

  run_tests: &run_tests
    - checkout

    - run:
        name: Install Bundler
        command: gem install bundler:1.17.3

    - run:
        name: Install Ruby Dependencies
        command: bundle install && cd spec/dummy && bundle install

    - run:
        name: Install Apprasals Dependencies
        command: bundle exec appraisal install

    - run:
        name: Setup Database
        command: cd spec/dummy && bundle exec rake db:create db:migrate --trace

    - run:
        name: Run Appraisals Tests
        command: bundle exec appraisal rspec

    - run:
        name: Run Dummy App Tests
        command: cd spec/dummy && bin/rspec

jobs:
  ruby_2_3:
    docker:
      - image: circleci/ruby:2.3
        environment:
          *test_env
      - *database
    steps:
      *run_tests

  ruby_2_4:
    docker:
      - image: circleci/ruby:2.4
        environment:
          *test_env
      - *database
    steps:
      *run_tests

  ruby_2_5:
    docker:
      - image: circleci/ruby:2.5
        environment:
          *test_env
      - *database
    steps:
      *run_tests

  ruby_2_6:
    docker:
      - image: circleci/ruby:2.6
        environment:
          *test_env
      - *database
    steps:
      *run_tests

  ruby_2_7:
    docker:
      - image: circleci/ruby:2.7
        environment:
          *test_env
      - *database
    steps:
      *run_tests

workflows:
  version: 2
  test-all:
    jobs:
      - ruby_2_3
      - ruby_2_4
      - ruby_2_5
      - ruby_2_6
      - ruby_2_7
