source 'https://rubygems.org'

gem 'handcuffs', path: "../../"
gem 'pg'
gem 'rails', '~> 5.2', '>= 5.2.4.1'
gem 'sprockets', '~> 3.7'

group :test do
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
end
