source 'https://rubygems.org'

gem 'appraisal'
gem 'handcuffs', path: "../../"
gem 'pg'
gem 'rails', "~> 6.1.0"
gem 'sprockets', '~> 3.7'

group :test do
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
end
