name: 'Auto Author Assign'
on:
  pull_request_target:
    types: [opened, reopened]
permissions:
  contents: read
jobs:
  assign-author:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@16f0022cf3d7970c106d8d1105f75a1165edb516 # v2.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
