name: 'Auto Author Assign'
on:
  pull_request_target:
    types: [opened, reopened]
permissions:
  contents: read
jobs:
  assign-author:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@ebd30f10fb56e46eb0759a14951f36991426fed0 # v2.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
