name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ruby: ['3.2', '3.3']
        gemfile:
          - gemfiles/rails_7.1.gemfile
          - gemfiles/rails_7.2.gemfile
          - gemfiles/rails_8.0.gemfile
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@d354de180d0c9e813cfddfcbdc079945d4be589b # v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
